[2024-10-04T18:42:02.278+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T18:42:02.323+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gps_kafka_spark_pipeline.run_spark_job scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T18:42:02.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gps_kafka_spark_pipeline.run_spark_job scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T18:42:02.336+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T18:42:02.354+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_spark_job> on 2024-10-03 00:00:00+00:00
[2024-10-04T18:42:02.360+0000] {standard_task_runner.py:64} INFO - Started process 72 to run task
[2024-10-04T18:42:02.364+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gps_kafka_spark_pipeline', 'run_spark_job', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp9vtn3hwv']
[2024-10-04T18:42:02.367+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask run_spark_job
[2024-10-04T18:42:02.446+0000] {task_command.py:426} INFO - Running <TaskInstance: gps_kafka_spark_pipeline.run_spark_job scheduled__2024-10-03T00:00:00+00:00 [running]> on host c5fb214ce388
[2024-10-04T18:42:02.546+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gps_kafka_spark_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T18:42:02.548+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T18:42:02.563+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T18:42:02.564+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark.py", line 15, in run_spark_job
    subprocess.run(["spark-submit", "/opt/airflow/dags/spark_job.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-04T18:42:02.585+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=gps_kafka_spark_pipeline, task_id=run_spark_job, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T184202, end_date=20241004T184202
[2024-10-04T18:42:02.598+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task run_spark_job ([Errno 13] Permission denied: 'spark-submit'; 72)
[2024-10-04T18:42:02.619+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-04T18:42:02.649+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T18:42:02.651+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
