[2024-10-04T18:47:09.221+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T18:47:09.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gps_kafka_spark_pipeline.run_spark_job scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T18:47:09.283+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gps_kafka_spark_pipeline.run_spark_job scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T18:47:09.284+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-04T18:47:09.305+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_spark_job> on 2024-10-03 00:00:00+00:00
[2024-10-04T18:47:09.310+0000] {standard_task_runner.py:64} INFO - Started process 92 to run task
[2024-10-04T18:47:09.321+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gps_kafka_spark_pipeline', 'run_spark_job', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp8eg0fv6a']
[2024-10-04T18:47:09.329+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask run_spark_job
[2024-10-04T18:47:09.521+0000] {task_command.py:426} INFO - Running <TaskInstance: gps_kafka_spark_pipeline.run_spark_job scheduled__2024-10-03T00:00:00+00:00 [running]> on host c5fb214ce388
[2024-10-04T18:47:09.737+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gps_kafka_spark_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T18:47:09.738+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T18:47:09.773+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T18:47:09.774+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark.py", line 15, in run_spark_job
    subprocess.run(["spark-submit", "/opt/airflow/dags/spark_job.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-04T18:47:09.808+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=gps_kafka_spark_pipeline, task_id=run_spark_job, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T184709, end_date=20241004T184709
[2024-10-04T18:47:09.829+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task run_spark_job ([Errno 13] Permission denied: 'spark-submit'; 92)
[2024-10-04T18:47:09.853+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-04T18:47:09.897+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T18:47:09.901+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
